export const faculty = [
    {
        url: 'src/assets/ithod.jpg',
        name: 'Prof. Dr. Savita Sangam',
        designation: 'Head Of Department',
        qualification: 'PhD',
        doj: '06-01-1997',
    },
    {
        url: 'src/assets/gowri-gorbal.jpg',
        name: ' Prof. M. R. Gorbal',
        designation: 'Associate Professor (Dean Student Affairs)',
        qualification: 'M.Tech',
        doj: '02-07-1996',
    },
    {
        url: 'src/assets/kirti-rjadnya.jpg',
        name: 'Prof. Kirti Rajadnya',
        designation: 'Associate Professor (NBA Coordinator)',
        qualification: 'M.E.',
        doj: '02-08-2000',
    },
    {
        url: 'src/assets/prajakta-khaire.png',
        name: 'Prof. Prajkta Khaire',
        designation: 'Assistant Professor (Deputy HOD)',
        qualification: 'M.E.',
        doj: '03-02-2006',
    },
    {
        url: 'src/assets/deepali-narkhede.jpg',
        name: 'Prof. Deepali Narkhede',
        designation: 'Assistant Professor',
        qualification: 'M.E.',
        doj: '01-08-2007',
    },
    {
        url: 'src/assets/aarti-devmane.jpg',
        name: 'Prof. Arti Devmane',
        designation: 'Assistant Professor',
        qualification: 'M.E.',
        doj: '01-08-2007',
    },
    {
        url: 'src/assets/Nidhi_sachdeh.jpg',
        name: 'Prof. Nidhi Sachdeh',
        designation: 'Assistant Professor',
        qualification: 'M.E.',
        doj: '01-07-2023',
    },
]